name: the_whiskey_manuscript_app
description: The Whiskey Manuscript â€” mobile app.
publish_to: "none"

version: 1.0.5

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  image_picker: ^1.1.2
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  uuid: ^4.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/TWM_Mark_Primary.svg
